Close #19
concordialang/ui-html pull request #24
Opened 2019-05-27 23:27 UTC by vcpablo

- introduce valid id formats validation
- remove input close tag

2019-05-28 13:47 UTC, thiagodp requested changes
Please provide tests along with the new code. 
Regarding the `.config.sample`, I recommend taking a look at the Slack discussion about the configuration format. I think it's better defining code for wrappers, widgets, etc., instead of CSS classes.

2019-05-31 02:25 UTC, WillianGoncalves commented on .config.sample
> +{
This file is not supposed to be committed now. It will be part of another issue.

2019-05-31 02:27 UTC, WillianGoncalves commented on src/widgets/prop.ts
> +
Remove empty lines.

2019-05-31 02:29 UTC, WillianGoncalves requested changes
Just a few changes, besides what @thiagodp said about tests.

2019-05-31 18:30 UTC, thiagodp approved these changes

2019-05-31 18:30 UTC, merged