WIP - Create input elements based on custom definitions file
concordialang/ui-html pull request #27
Opened 2019-06-08 15:10 UTC by WillianGoncalves

2019-06-08 15:14 UTC, WillianGoncalves commented on src/interfaces/custom_config.ts
> +export interface CustomConfig {
Would "CustomDefinitions" be a better name for this interface? Then we will have "CustomDefinitionsLoader" instead of "ConfigLoader".

2019-06-08 15:15 UTC, WillianGoncalves commented on src/interfaces/custom_config.ts
> +export interface WidgetConfig {
Same thing here: "WidgetDefinition", "WidgetCustomDefinition" or keep "WidgetConfig".

2019-06-08 20:15 UTC, thiagodp requested changes

2019-06-08 20:15 UTC, thiagodp commented on src/generator.ts
>  export default class Generator implements Prototyper {
It appears that `UIPrototyper` could be a better name. Whether `Prototyper` is not a generic prototyper, then the interface could be renamed to `UIPrototyper` and `Generator` could be named `HtmlUIPrototyper`.

2019-06-08 20:15 UTC, thiagodp commented on src/generator.ts
>  	private async createHtmlFile(fileName: string, widgets: Widget[]): Promise<string> {
This method indicates my point above.

2019-06-08 20:15 UTC, thiagodp commented on src/interfaces/custom_config.ts
> +export interface CustomConfig {
I think that `AppConfig` would be better.

BTW, we were using `dashed-case` for file names, instead of `snake_case`.

2019-06-08 20:15 UTC, thiagodp commented on src/interfaces/custom_config.ts
> +export interface WidgetConfig {
`WidgetConfig` sounds good

2019-06-08 20:15 UTC, thiagodp commented on src/interfaces/custom_config.ts
> +export const WIDGET_OPENING = 'opening'
Are these constants really needed?

2019-06-08 20:15 UTC, thiagodp commented on src/utils/config_loader.ts
> +export class ConfigLoader {
IMO, `AppConfigLoader` would be better.
BTW, prefer dashed-case for file names.

2019-06-08 20:15 UTC, thiagodp commented on src/utils/config_loader.ts
> +	public getInputDefinition(): WidgetConfig {
That's not necessary. You can just traverse all the properties in `widget`, instead of creating a method to get each one.

2019-06-08 20:15 UTC, thiagodp commented on src/utils/create_label.ts
> +export function createLabel(name: string, id: string): string {
- dashed-case (file name)
- Shouldn't this file be placed where the widgets are? (Maybe in a file named `label.ts`)

2019-06-08 20:15 UTC, thiagodp commented on src/widgets/input.ts
> +	private createInput(): string {
This approach is not effective anymore. All the widgets' definition are now loaded from the config file. Every widget tag can contain a variable where the properties are placed. The rendering becomes generic, and can be implemented in a single class. The widgets need only to interpret the properties and to render them, not the widget itself.

2019-06-18 00:02 UTC, WillianGoncalves commented on src/generator.ts
>  export default class Generator implements Prototyper {
I just opened an issue to do it: https://github.com/concordialang/ui-core/issues/19

2019-06-27 00:56 UTC, thiagodp approved these changes

2019-06-27 00:56 UTC, merged