feat(element-type): introduce button element type
concordialang/ui-html pull request #8
Opened 2019-04-03 14:58 UTC by vcpablo

2019-04-04 23:41 UTC, WillianGoncalves commented on src/classes/element-factory.ts
> +    console.log(element.widget)
Remove

2019-04-08 18:05 UTC, thiagodp requested changes

2019-04-08 18:05 UTC, thiagodp commented on src/classes/element-factory.ts
> +import {Element} from '/Users/vcpablo/Code/concordia-ui/ui-core/src'
- [x] Better adding `ui-core` as a dependency via `npm install`. The repo can be in your machine.

2019-04-08 18:05 UTC, thiagodp commented on src/commands/generate.ts
> +import { ProcessResult } from '../../../ui-core/src'
- [x] It's better importing `ui-core` from a local repository

2019-04-08 18:05 UTC, thiagodp commented on src/classes/html-elements/input.ts
> +      case 'string':
It would be better representing the possible values with an `enum` type.

2019-04-08 18:05 UTC, thiagodp commented on src/commands/generate.ts
>    static description = 'Generate html files'
Better `public readonly` than `static`

2019-04-08 18:05 UTC, thiagodp commented on src/classes/element-factory.ts
> +    case 'button':
- [ ] It's better representing possible widget types with an `enum` type.

2019-04-08 18:05 UTC, thiagodp commented on src/classes/generator.ts
> +import {Feature, Prototyper} from '/Users/vcpablo/Code/concordia-ui/ui-core/src'
- [ ] It's better adding `ui-core` as a dependency via `npm install`

2019-04-08 18:05 UTC, thiagodp commented on src/classes/generator.ts
> +  public write(feature: Feature, elements: HtmlElement[]) {
- [ ] Please use `async` writes/reads. It's easier to use a promisified version of `writeFile`.

2019-04-10 23:22 UTC, WillianGoncalves commented on src/commands/generate.ts
>    static description = 'Generate html files'
The static properties `description` and `flags` are automatically generated by oclif. I've tried replace `static` with `public readonly`, but it does not work.

2019-04-11 17:05 UTC, thiagodp requested changes
Some changes are needed

2019-04-11 17:05 UTC, thiagodp commented on src/commands/generate.ts
>    static description = 'Generate html files'
Okay

2019-04-11 17:05 UTC, thiagodp commented on src/classes/element-factory.ts
> +import {Element} from '/Users/vcpablo/Code/concordia-ui/ui-core/src'
It should be
```typescript
import { Element } from 'concordialang-ui-core'
```

2019-04-11 17:05 UTC, thiagodp commented on src/classes/element-factory.ts
> +import {Element} from '/Users/vcpablo/Code/concordia-ui/ui-core/src'
It should be
```typescript
import { Element } from 'concordialang-ui-core'
```

2019-04-11 17:05 UTC, thiagodp commented on src/classes/generator.ts
> +import {Feature, Prototyper} from '/Users/vcpablo/Code/concordia-ui/ui-core/src'
It should be
```typescript
import { Feature, Prototyper } from 'concordialang-ui-core'
```

2019-04-11 17:05 UTC, thiagodp commented on src/classes/generator.ts
> +import * as fs from 'fs'
I recommend to inject `fs` as a constructor parameter that assumes it as a default. Thus, `memfs` can be used instead, for testing purposes.

2019-04-11 17:05 UTC, thiagodp commented on src/classes/generator.ts
> +        fs.appendFileSync(path, `<div>${element.toString()}</div>`);
Please use an `async` version

2019-04-11 17:05 UTC, thiagodp commented on src/classes/generator.ts
>      return new Promise((resolve, reject) => {
Just write `return elements`

2019-04-11 17:05 UTC, thiagodp commented on src/commands/generate.ts
> +import { ProcessResult } from '../../../ui-core/src'
It should be
```typescript
import { ProcessResult } from 'concordialang-ui-core'
```

2019-04-11 17:05 UTC, thiagodp commented on package.json
> +    "fs": "0.0.1-security",
Why?

2019-04-11 17:41 UTC, merged